/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.tuti;

import com.tuti.api.TutiApiClient;
import com.tuti.api.authentication.*;


import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.fail;

public class ApiTest {
     static TutiApiClient client;

    @BeforeAll
    static void setup(){
        client = new TutiApiClient(true);
        client.setSingleThreaded(true);
    }
    @Test
     void testSignInApi(){
        SignInInfo credentials = new SignInInfo("adonese","12345678");

        client.SignIn(credentials,(SignInResponse response) -> {
            client.setAuthToken(response.getAuthorizationJWT());
            User user = response.getUser();
            assertEquals("adonese",user.getUsername());
            assertEquals("Mohamed Yousif",user.getFullname());
            assertEquals("mmbusif@gmail.com",user.getEmail());
            assertEquals("0925343834",user.getMobileNumber());
            assertEquals(true,user.getIsMerchant());
            assertEquals(0,user.getId());
        },(String error,Exception e,int responseCode) -> {fail("sign in failed");});


        //

    }

    @Test void testSignUpApi(){
        SignUpInfo info = new SignUpInfo();

        info.setMobileNumber("0129751986");
        info.setPassword("Ramiimar1234.");
        info.setUsername("rami3sam");
        info.setFullname("Rami Essamedeen");
        info.setEmail("rami3sam@gmail.com");
        info.setMerchant(true);

        client.Signup(info,(SignUpResponse response) -> {
            User user = response.getUser();
            assertEquals("rami3sam",user.getUsername());
            assertEquals("Rami Essamedeen",user.getFullname());
            assertEquals("rami3sam@gmail.com",user.getEmail());
            assertEquals("0129751986",user.getMobileNumber());
            assertEquals(true,user.getIsMerchant());
        },(String error,Exception e, int responseCode ) -> {fail("sign up failed");} );

    }


    @Test void testGetCards(){
        SignInInfo credentials = new SignInInfo("adonese","12345678");

        client.SignIn(credentials,(SignInResponse response) -> {
                    client.setAuthToken(response.getAuthorizationJWT());
                },(param, exception, responseCode) -> {fail("Sign in failed");});

        client.getCards(cards -> {
            assertEquals("adonese",cards.getCards().get(0).getName());
            assertEquals("22222222222222222",cards.getCards().get(0).getPAN());

        } , (param, exception, responseCode) -> {fail();});
    }

}
