/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.tuti;

import com.tuti.api.TutiApiClient;
import com.tuti.api.authentication.UserCredentials;

public class Library {
    public static void main(String[] args) {
		TutiApiClient client = new TutiApiClient(true);
		System.out.println(client.SignIn(new UserCredentials("adonese","12345678")).getUser().getMobileNumber());
	}
}
