/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.tuti;

import com.tuti.api.TutiApiClient;
import com.tuti.api.authentication.SignInRequest;
import com.tuti.api.authentication.User;
import com.tuti.api.data.Card;
import com.tuti.api.ebs.EBSRequest;
import com.tuti.util.Utils;

public class Library {

    public static String jwt;
    public static void main(String[] args) {
        TutiApiClient client = new TutiApiClient();
        client.setSingleThreaded(true);

        SignInRequest credentials = new SignInRequest("adonese1","12345678");
        client.setAuthToken(null);

        client.SignIn(credentials,( signInResponse , rawResponse) -> {
            User user = signInResponse.getUser();

            System.out.println("User information from sign in endpoint (adonese case):\n"+user);
        },( error, exception, rawResponse) -> {System.out.println(rawResponse.getHeaders());
            System.out.println(rawResponse.getHeaders());});


	}
}
