/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.tuti

import com.tuti.api.TutiApiClient
import com.tuti.api.authentication.SignInRequest
import com.tuti.api.authentication.SignInResponse
import com.tuti.api.data.Contact

object Library {
    var jwt: String? = null

    @JvmStatic
    fun main(args: Array<String>) {
        val client = TutiApiClient()
        client.SignIn(SignInRequest(mobile = "0923377628", password = "Rami1234."),
                onResponse = { signInResponse: SignInResponse ->
                    val token = signInResponse.authorizationJWT
                    client.authToken = token
                    client.syncContacts(listOf(Contact("Rami", "0923377628"),
                            Contact("Mohammed Salah", "0968199068"),
                             Contact("Khalid", "0123456789")),
                            onResponse = { contacts ->
                                print(contacts)
                            },
                            onError = { tutiResponse, exception -> })
                },
                onError = { tutiResponse, exception -> })
    }
}

