/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.tuti;

import com.tuti.api.TutiApiClient;
import com.tuti.api.authentication.SignInRequest;
import com.tuti.api.data.Card;
import com.tuti.api.ebs.EBSRequest;

public class Library {

    public static String jwt;
    public static void main(String[] args) {
        TutiApiClient client = new TutiApiClient();
        client.setSingleThreaded(true);

        client.getPublicKey(new EBSRequest(),(objectReceived, rawResponse) ->  {
            System.out.println(objectReceived.getEbsResponse().getPubKeyValue());
        },(errorReceived, exception, rawResponse) -> {

        });
	}
}
